plans:
  directory: migrations/
  filenamePattern: "*.md"

defaults:
  agent: devin
  prParallelism: 1
  rebase:
    when: behind-base-branch
    allowManual: true
  labels: [hachiko, self-test, migration]
  requirePlanReview: true

aiConfigs:
  provider: launchdarkly
  flagKeyPrefix: hachiko_self_test_

policy:
  allowWorkflowEdits: false
  network: restricted
  maxAttemptsPerStep: 2
  stepTimeoutMinutes: 30
  perRepoMaxConcurrentMigrations: 1
  riskyGlobs:
    - ".github/workflows/**"
    - ".git/**"
    - "**/*.sh"
    - "package.json"
    - "package-lock.json"
    - "pnpm-lock.yaml"
    - ".env*"
    - "**/*.key"
    - "**/*.pem"
  allowlistGlobs:
    - "src/**"
    - "self-test/**"
    - "examples/**"
    - "test/**"
    - "migrations/**"
    - "docs/**"
    - "*.md"
    - "scripts/**"

dependencies:
  conflictResolution: fail
  updateStrategy: manual

agents:
  # Cloud agents for production testing
  devin:
    kind: cloud
    provider: devin
    apiVersion: v3beta1
    timeout: 900
    # For Devin API v3 with service users:
    # apiKey: configured via DEVIN_API_KEY environment variable
    # organizationId: configured via DEVIN_ORG_ID environment variable (optional, depends on service user type)

  cursor:
    kind: cloud
    provider: cursor
    timeout: 1200
    repositoryUrl: "https://github.com/launchdarkly-labs/hachiko"
    branch: main
    # apiKey: configured via CURSOR_API_KEY environment variable
    # webhookUrl: configured via CURSOR_WEBHOOK_URL environment variable (optional - for status notifications)

  codex:
    kind: cloud
    provider: codex
    model: gpt-4-turbo
    maxTokens: 4000
    temperature: 0.1
    timeout: 300
    # apiKey: configured via OPENAI_API_KEY environment variable

  # Mock agent for safe testing without external APIs
  mock:
    kind: cli
    command: echo
    args: ["Mock agent executed successfully for:", "{prompt}"]
    timeout: 60

  # Legacy CLI agents (deprecated)
  claude-cli:
    kind: cli
    command: claude
    args: ["code", "--apply"]
  cursor-cli:
    kind: cli
    command: cursor
    args: ["--headless", "apply"]
